### ISSUE TITLE
RFC: Integrate binding with platform

### ISSUE THREAD

**Issue by hardikmaheshwari** [finos/legend-engine#703]
### Overview

A Binding is a concept used to define support in the platform for data in some format. Data is either described using a formal schema or understood through conventions.

Internal to the platform we have the data model to describe the data structurally and instances of it to represent data values. Their external equivalents are the schema (for example a JSON Schema) and the serialized form of the data (for example a JSON document). Models can be generated from schemas and vice versa.

As a part of the development for this RFC, we plan to integrate/refactor bindings into the legend platform so that users can integrate use-cases depending on schemas/data defined in some format

### Implementation plan

We plan to tackle the development of binding integration in the following phases. 
The ideology behind the implementation plan is to take a depth approach and get simple use-cases working first and then add features to bring feature parity compared to existing support for Flatdata/ Json/ Xsd.

These tasks would be expanded into individual issues containing concrete details. 

### Phase I: Simple use-cases supported end-to-end with binding
- [x] Finalize & document query semantics and the role of bindings within it (https://github.com/finos/legend-engine/blob/master/docs/queries/queries.md )
- [x] Uplift Routing phase to work with both binding & store
- [x] Add support for ->internalize function to work with static string, URL and byte-stream
- [x] Add support for ->externalize function to work with simple use-cases (checked queries are out of scope for this phase)
- [x] Consolidate execution plan / nodes for binding flow (includes serialization / deserialization)
- [x] Uplift services to work with the binding flow (in absence of mapping/runtime & with byte-stream as a query parameter)
- [x] Define testing strategy for services with bindings 
- [x] Services with binding queries can be executed via jars.
- [x] Studio supports binding queries in text mode
- [x] Define and document the External Format Contract and the steps needed to add new ExternalFormat support in legend

### Phase II: Feature parity compared to existing support for FlatData / Json / Xsd
- [x] Support checked result with externalize
- [ ] Studio supports binding queries seamlessly (Support should be at par with queries backed by stores)
- [ ] Uplift binding / externalize function to account for custom configurations

### Phase III: Delete code for legacy FlatData / Json / Xsd
- [x] Fix Binding metamodel and detach it from store hierarchy 
- [x] Remove External Format Connection
- [ ] Deprecate legacy code & migrate existing use cases to strategic flow
- [ ] Safely delete legacy code 

### Additional context

1. Binding: https://github.com/finos/legend-engine/blob/master/docs/bindings/bindings.md 
2. Query Semantics: https://github.com/finos/legend-engine/blob/master/docs/queries/queries.md

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.

**Comment by finos-admin** [comment]
This issue is stale because it has been open for 30 days with no activity. Please remove stale label or add any comment to keep this open. Otherwise this will be closed in 5 days.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
